### ISSUE TITLE
Using "init-course" with a "finished" course causes issues

### ISSUE THREAD

**Issue by htdebeer-tue** [htdebeer-tue/repobee-canvas#8]
Bert reported some issues that are likely related to using command `repobee canvas init-course` with an URL to a course that is "finished":

- The access token did not work. Bert got a 401 Unauthorized error message from Canvas.
- There were also no students

**Comment by davbeek** [comment]
It could be that this was caused by an error in the access token. I remember being rather annoyed when I could not see if I had pasted the access token correctly, seeing only XXXXXXXXXXXXXXX. I could have pasted something completely wrong or I could have pasted the access token twice, with no possibility of noticing. I think it would be a huge improvement if the access token was not obfuscated. I don't remember if Repobee also obfuscated the access token when initializing Repobee. If so, the same holds for Repobee.

**Comment by htdebeer-tue** [comment]
I agree, a visible access token is nice when you're unsure if you've entered or copied the right one. The downside is that others might see it on your computer. But the access tokens are visible in plain text anyway when you view the RepoBee configuration files, so that cat's already out of the bag.

Anyway, I do expect the canvas plugin to work regardless if a course is finished, unpublished, or otherwise not currently available. But I will check these cases anyway, just to make sure.

**Question**: Should I warn the user when they use a finished or unpublished course? And are there any other "inactive" states a Canvas course can be in?

**Comment by davbeek** [comment]
> so that cat's already out of the bag.

Indeed, and you'd need super powers to be able to remember a 70 arbitrary character access token!

I would prefer not to have a warning when using a finished or unpublished course, because I expect many users to test the functionality on an unpublished or finished course, and when a user gets a warning on something that he very well knows he is doing, it tends to be irritating.

I think that with finished and unpublished, you have all inactive states.

**Comment by htdebeer-tue** [comment]
I checked and, as expected, the `init-course` command works with an unpublished course and a finished course and a course without any students.

I do agree we do not need warnings about courses. Teachers should know if their course is active or not, and it makes sense to play around with a finished or unpublished course.
